In [161]:
import pandas as pd
import numpy as np

X_tr = np.loadtxt('X_train.txt', delimiter=' ')
Y_tr = np.loadtxt('y_train.txt')
train_size = int(X_tr.shape[0]*0.8)
X_train = X_tr[0:train_size]
Y_train = Y_tr[0:train_size]
X_val = X_tr[train_size:]
Y_val = Y_tr[train_size:]

X_test = np.loadtxt('X_test.txt', delimiter=' ')
Y_test = np.loadtxt('y_test.txt')

print(Y_test)

[5. 5. 5. ... 2. 2. 2.]


In [171]:
from sklearn import svm
#### Linear SVM Classifier ####

indx=0
accuracy = np.zeros(11)
for i in range(-5,5):
        print('Training svm... for C:{}'.format(2**i))
        lsvm_clf = svm.SVC(C=2**i, kernel='linear')
        lsvm_clf.fit(X_train,Y_train)

        print('Creating predict model...')
        pred = lsvm_clf.predict(X_train)
        print(pred)

Training svm... for C:0.03125
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:0.0625
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:0.125
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:0.25
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:0.5
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:1
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:2
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:4
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:8
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]
Training svm... for C:16
Creating predict model...
[5. 5. 5. ... 5. 5. 5.]


In [170]:
#knn
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
KNeighborsClassifier()
knn_pred = knn.predict(X_test);
print(knn_pred)


[5. 5. 5. ... 2. 2. 1.]


In [175]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,Y_train)

#Predict the response for test dataset
dt_y_pred = clf.predict(X_test)

print(dt_y_pred)


[4. 5. 5. ... 2. 2. 2.]


In [181]:
#Random Forest

from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, Y_train)
rf_y_pred = regressor.predict(X_test)

print(rf_y_pred)

[4.85 4.95 5.   ... 2.05 1.35 1.3 ]
